# Setting up a meaningful DF

In [256]:
import numpy as np
import pandas as pd
import json
import codecs
import pandas as pd
import matplotlib as m
import matplotlib.pyplot as plt
from pandas.io.json import json_normalize

#Yenny's dups file
json_file = "/Users/kimia/Desktop/Work5/duplicates_batch_2018-05-18.json"
df = pd.read_json(json_file, lines=True)
dfsub = json_normalize(df.submission)

#everything but payload ('twas messy, so I split it then merge)
metadf = dfsub[[ 'task_id', 'updated_at', 'user_id', 'created_at', 'id']]

In [257]:
dfsub = pd.DataFrame(dict(df.submission[0:])).T
dfpayloads = pd.DataFrame()

# I know this isn't efficient. But it helps split out the payloads (multiple per task_id). 
for i in range(dfsub.shape[0]):
    f = pd.DataFrame(dfsub.payload[i]).T
    f['id'] = dfsub.id[i]
    f['task_id'] = dfsub.task_id[i]
    f['user_id'] = dfsub.user_id[i]
    f['created_at'] = dfsub.created_at[i]
    f['updated_at'] = dfsub.updated_at[i]
    dfpayloads = pd.concat([dfpayloads, f])
    
dfpayloads = dfpayloads.reset_index()
dfpayloads = dfpayloads.rename(index=str, columns={"index": "payload"})
dfpayloads['count'] = 1 # this is to signify one input per user
#dfpayloads.to_csv('dfpayloads.csv')

dfpayloads

,payload,annotation,created_at,id,task_id,updated_at,user_id,count
0,05132050-c570-4f76-a3fe-7962271b866f,non-duplicate,2018-05-03T18:59:09.772Z,145881,56592,2018-05-03T19:43:03.775Z,20,1
1,21126bec-7c04-44a7-8fb2-1aec1dfd8e84,non-duplicate,2018-05-03T18:59:09.772Z,145881,56592,2018-05-03T19:43:03.775Z,20,1
2,3547e0aa-9f2a-4e65-8ab1-da5831b4d379,non-duplicate,2018-05-03T18:59:09.772Z,145881,56592,2018-05-03T19:43:03.775Z,20,1
3,42714808-8c62-48e4-b564-898476195788,non-duplicate,2018-05-03T18:59:09.772Z,145881,56592,2018-05-03T19:43:03.775Z,20,1
4,7e58fb9c-6979-486d-ae06-b2528c0651d6,non-duplicate,2018-05-03T18:59:09.772Z,145881,56592,2018-05-03T19:43:03.775Z,20,1
5,86b9a2ed-905a-4e1b-9437-257b3000b9ce,non-duplicate,2018-05-03T18:59:09.772Z,145881,56592,2018-05-03T19:43:03.775Z,20,1
6,9a5d1cb5-d8a8-4964-b2ea-b4428f5a2708,non-duplicate,2018-05-03T18:59:09.772Z,145881,56592,2018-05-03T19:43:03.775Z,20,1
7,c5827784-7c2a-4dd9-b38d-fb956f226cb0,duplicate,2018-05-03T18:59:09.772Z,145881,56592,2018-05-03T19:43:03.775Z,20,1
8,d1139480-f5a9-4448-8ed2-6c13f1849432,non-duplicate,2018-05-03T18:59:09.772Z,145881,56592,2018-05-03T19:43:03.775Z,20,1
9,d57ca369-d6f1-4e1f-aae8-29e1bef3e9ca,non-duplicate,2018-05-03T18:59:09.772Z,145881,56592,2018-05-03T19:43:03.775Z,20,1
10,d74fc8fc-14de-4e5b-98c9-d24b0215af07,non-duplicate,2018-05-03T18:59:09.772Z,145881,56592,2018-05-03T19:43:03.775Z,20,1
11,d881697d-370c-41f8-bff5-953b0b7d2ead,non-duplicate,2018-05-03T18:59:09.772Z,145881,56592,2018-05-03T19:43:03.775Z,20,1
12,ff566377-b474-43de-89be-7b6e79b53199,non-duplicate,2018-05-03T18:59:09.772Z,145881,56592,2018-05-03T19:43:03.775Z,20,1
13,05132050-c570-4f76-a3fe-7962271b866f,non-duplicate,2018-05-03T19:00:44.413Z,145885,56592,2018-05-03T19:19:30.178Z,40,1
14,21126bec-7c04-44a7-8fb2-1aec1dfd8e84,non-duplicate,2018-05-03T19:00:44.413Z,145885,56592,2018-05-03T19:19:30.178Z,40,1
15,3547e0aa-9f2a-4e65-8ab1-da5831b4d379,non-duplicate,2018-05-03T19:00:44.413Z,145885,56592,2018-05-03T19:19:30.178Z,40,1
16,42714808-8c62-48e4-b564-898476195788,non-duplicate,2018-05-03T19:00:44.413Z,145885,56592,2018-05-03T19:19:30.178Z,40,1
17,7e58fb9c-6979-486d-ae06-b2528c0651d6,non-duplicate,2018-05-03T19:00:44.413Z,145885,56592,2018-05-03T19:19:30.178Z,40,1
18,86b9a2ed-905a-4e1b-9437-257b3000b9ce,non-duplicate,2018-05-03T19:00:44.413Z,145885,56592,2018-05-03T19:19:30.178Z,40,1
19,9a5d1cb5-d8a8-4964-b2ea-b4428f5a2708,non-duplicate,2018-05-03T19:00:44.413Z,145885,56592,2018-05-03T19:19:30.178Z,40,1
20,c5827784-7c2a-4dd9-b38d-fb956f226cb0,duplicate,2018-05-03T19:00:44.413Z,145885,56592,2018-05-03T19:19:30.178Z,40,1
21,d1139480-f5a9-4448-8ed2-6c13f1849432,non-duplicate,2018-05-03T19:00:44.413Z,145885,56592,2018-05-03T19:19:30.178Z,40,1
22,d57ca369-d6f1-4e1f-aae8-29e1bef3e9ca,non-duplicate,2018-05-03T19:00:44.413Z,145885,56592,2018-05-03T19:19:30.178Z,40,1
23,d74fc8fc-14de-4e5b-98c9-d24b0215af07,non-duplicate,2018-05-03T19:00:44.413Z,145885,56592,2018-05-03T19:19:30.178Z,40,1
24,d881697d-370c-41f8-bff5-953b0b7d2ead,non-duplicate,2018-05-03T19:00:44.413Z,145885,56592,2018-05-03T19:19:30.178Z,40,1
25,ff566377-b474-43de-89be-7b6e79b53199,non-duplicate,2018-05-03T19:00:44.413Z,145885,56592,2018-05-03T19:19:30.178Z,40,1
26,05132050-c570-4f76-a3fe-7962271b866f,non-duplicate,2018-05-03T19:02:06.179Z,145887,56592,2018-05-03T19:18:03.427Z,43,1
27,21126bec-7c04-44a7-8fb2-1aec1dfd8e84,non-duplicate,2018-05-03T19:02:06.179Z,145887,56592,2018-05-03T19:18:03.427Z,43,1
28,3547e0aa-9f2a-4e65-8ab1-da5831b4d379,non-duplicate,2018-05-03T19:02:06.179Z,145887,56592,2018-05-03T19:18:03.427Z,43,1
29,42714808-8c62-48e4-b564-898476195788,non-duplicate,2018-05-03T19:02:06.179Z,145887,56592,2018-05-03T19:18:03.427Z,43,1
...,...,...,...,...,...,...,...,...
168505,e02f1e01-241e-4ebc-8ec1-c57cffd1d12f,non-duplicate,2018-05-15T18:41:12.426Z,158543,59032,2018-05-15T18:44:11.329Z,43,1
168506,f77a55f5-0ef7-47b1-bb9c-9fddad63cbf7,non-duplicate,2018-05-15T18:41:12.426Z,158543,59032,2018-05-15T18:44:11.329Z,43,1
168507,04aa40de-94b4-468d-9133-fc0f003bed40,non-duplicate,2018-05-15T18:41:40.980Z,158546,59032,2018-05-15T18:43:54.507Z,47,1
168508,0f8312b7-18fb-495a-8502-c9a45eddcba4,non-duplicate,2018-05-15T18:41:40.980Z,158546,59032,2018-05-15T18:43:54.507Z,47,1
168509,14b0a60a-0d31-4605-b977-c73917a91f96,duplicate,2018-05-15T18:41:40.980Z,158546,59032,2018-05-15T18:43:54.507Z,47,1
168510,204ef65a-4be6-4f9d-873a-c7f376f0458f,non-duplicate,2018-05-15T18:41:40.980Z,158546,59032,2018-05-15T18:43:54.507Z,47,1
168511,457dfc73-0c10-4993-9bda-f2eff9a90b6f,non-duplicate,2018-05-15T18:41:40.980Z,158546,59032,2018-05-15T18:43:54.507Z,47,1
168512,51d1fe2c-9498-4282-af48-ecf5343d3444,non-duplicate,2018-05-15T18:41:40.980Z,158546,59032,2018-05-15T18:43:54.507Z,47,1
168513,722b5eba-cec6-46e3-b834-7dd403099c05,non-duplicate,2018-05-15T18:41:40.980Z,158546,59032,2018-05-15T18:43:54.507Z,47,1
168514,8c52455a-42d2-4096-80fb-cd998a594e6b,non-duplicate,2018-05-15T18:41:40.980Z,158546,59032,2018-05-15T18:43:54.507Z,47,1
168515,919b9f36-985d-4465-be74-dfa2a2fd6573,duplicate,2018-05-15T18:41:40.980Z,158546,59032,2018-05-15T18:43:54.507Z,47,1
168516,a6da4f92-4e6b-4338-95aa-a475f2d3e027,non-duplicate,2018-05-15T18:41:40.980Z,158546,59032,2018-05-15T18:43:54.507Z,47,1
168517,bd5ee73b-ba74-4c98-a81c-e5ec024c790f,non-duplicate,2018-05-15T18:41:40.980Z,158546,59032,2018-05-15T18:43:54.507Z,47,1
168518,df6e452a-508b-4573-9c6d-52b2d80abac0,non-duplicate,2018-05-15T18:41:40.980Z,158546,59032,2018-05-15T18:43:54.507Z,47,1
168519,e02f1e01-241e-4ebc-8ec1-c57cffd1d12f,non-duplicate,2018-05-15T18:41:40.980Z,158546,59032,2018-05-15T18:43:54.507Z,47,1
168520,f77a55f5-0ef7-47b1-bb9c-9fddad63cbf7,non-duplicate,2018-05-15T18:41:40.980Z,158546,59032,2018-05-15T18:43:54.507Z,47,1
168521,04aa40de-94b4-468d-9133-fc0f003bed40,non-duplicate,2018-05-15T18:37:17.922Z,158486,59032,2018-05-15T18:37:57.587Z,46,1
168522,0f8312b7-18fb-495a-8502-c9a45eddcba4,non-duplicate,2018-05-15T18:37:17.922Z,158486,59032,2018-05-15T18:37:57.587Z,46,1
168523,14b0a60a-0d31-4605-b977-c73917a91f96,non-duplicate,2018-05-15T18:37:17.922Z,158486,59032,2018-05-15T18:37:57.587Z,46,1
168524,204ef65a-4be6-4f9d-873a-c7f376f0458f,non-duplicate,2018-05-15T18:37:17.922Z,158486,59032,2018-05-15T18:37:57.587Z,46,1
168525,457dfc73-0c10-4993-9bda-f2eff9a90b6f,non-duplicate,2018-05-15T18:37:17.922Z,158486,59032,2018-05-15T18:37:57.587Z,46,1
168526,51d1fe2c-9498-4282-af48-ecf5343d3444,non-duplicate,2018-05-15T18:37:17.922Z,158486,59032,2018-05-15T18:37:57.587Z,46,1
168527,722b5eba-cec6-46e3-b834-7dd403099c05,non-duplicate,2018-05-15T18:37:17.922Z,158486,59032,2018-05-15T18:37:57.587Z,46,1
168528,8c52455a-42d2-4096-80fb-cd998a594e6b,non-duplicate,2018-05-15T18:37:17.922Z,158486,59032,2018-05-15T18:37:57.587Z,46,1
168529,919b9f36-985d-4465-be74-dfa2a2fd6573,non-duplicate,2018-05-15T18:37:17.922Z,158486,59032,2018-05-15T18:37:57.587Z,46,1
168530,a6da4f92-4e6b-4338-95aa-a475f2d3e027,non-duplicate,2018-05-15T18:37:17.922Z,158486,59032,2018-05-15T18:37:57.587Z,46,1
168531,bd5ee73b-ba74-4c98-a81c-e5ec024c790f,non-duplicate,2018-05-15T18:37:17.922Z,158486,59032,2018-05-15T18:37:57.587Z,46,1
168532,df6e452a-508b-4573-9c6d-52b2d80abac0,non-duplicate,2018-05-15T18:37:17.922Z,158486,59032,2018-05-15T18:37:57.587Z,46,1
168533,e02f1e01-241e-4ebc-8ec1-c57cffd1d12f,non-duplicate,2018-05-15T18:37:17.922Z,158486,59032,2018-05-15T18:37:57.587Z,46,1
168534,f77a55f5-0ef7-47b1-bb9c-9fddad63cbf7,non-duplicate,2018-05-15T18:37:17.922Z,158486,59032,2018-05-15T18:37:57.587Z,46,1

# Summary Stats

In [254]:
# Percent of time there is not consensus on a single payload within a task

# Group by task, and payload. Annotations will indicate whether consensus or not
df = ((dfpayloads.groupby([ 'task_id', 'payload','annotation']).size()).to_frame()).reset_index()
df['count'] = df[0]

# ID consensus, discrepancies
discrepancies = df[df['count']!=5] 
discrepancies = ((discrepancies.groupby([ 'task_id', 'payload']).count())).reset_index()
        # ^ this is because payloads can be duplicated (so I can't do unique)
consensus = df[df['count']==5] #29918
consensus= consensus.groupby([ 'task_id', 'payload' ]).sum()['count'].reset_index()

# total
total = df.groupby([ 'task_id', 'payload' ]).sum()['count'].reset_index()
         # ^ this is because payloads can be duplicated (so I can't do unique)

consensus1 = 1-(discrepancies.payload.shape[0] /(total.payload.shape[0]))
consensus2 = 1-(discrepancies.payload.shape[0] /(consensus.payload.shape[0] + discrepancies.payload.shape[0] ))

print((consensus1*100),'% of the time there is consensus on a single payload within a task.',
      'Assuming the consensus is generally correct, this suggests Taskus is an effective resource')

89.05574923274038 % of the time there is consensus on a single payload within a task. Assuming the consensus is generally correct, this suggests Taskus is an effective resource

In [296]:
## For each user, how often do How often is this person the only person who disagrees?
lowagreement = dfpayloads.groupby(['payload', 'task_id', 'annotation']).size().to_frame(name = 'count').reset_index()
lowagreement = lowagreement[lowagreement['count'] == 1]
result = pd.merge(lowagreement,dfpayloads,  how = 'right', on=['payload', 'task_id','annotation'])

differ_from_others = ((result.groupby('user_id').count()['count_x'].to_frame())).sort_values('count_x', ascending=False).reset_index()

#total number of annotations that each person does 
total = dfpayloads.groupby(['user_id']).count()['payload'].to_frame(name = 'count').reset_index()

#calculations
perfmstat = pd.merge(differ_from_others,total,  on=['user_id'])
perfmstat['%'] = perfmstat['count_x']/perfmstat['count']
perfmstat = perfmstat.rename(index=str, columns={"count_x": "#timediffer", 'count': 'totalannot'})
print("Top users who are the *only* Taskus employee diverging from consensus (5)")
perfmstat.sort_values('%', ascending=False)

Top users who are the *only* Taskus employee diverging from consensus (5)

    user_id  #timediffer  totalannot         %
0        30          270        5997  0.045023
2        22          166        4771  0.034794
1        29          192        7571  0.025360
3        37          152        7008  0.021689
6        38          105        5967  0.017597
4        46          120        7671  0.015643
5        21          116        7823  0.014828
8        36           80        6031  0.013265
12       40           71        6027  0.011780
7        39           83        7582  0.010947
11       16           74        6866  0.010778
13       49           69        6862  0.010055
16       17           64        6581  0.009725
18       43           54        5559  0.009714
17       26           56        5775  0.009697
9        45           74        7655  0.009667
25       19            5         522  0.009579
10       44           74        7869  0.009404
14       33           66        7648  0.008630
15       20           66        7729  0.008539
23       31           42        5618  0.007476
22       41           44        5952  0.007392
24       47           28        4264  0.006567
20       58           50        7686  0.006505
19       23           50        8133  0.006148
21       25           45        7368  0.006107